services:
  - type: web
    name: lexiquery-api
    runtime: python
    buildCommand: pip install -r requirements.txt && python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('all-MiniLM-L6-v2')"
    startCommand: gunicorn api:app -k uvicorn.workers.UvicornWorker -w 1 --bind 0.0.0.0:$PORT --timeout 300
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: LLM_MODEL
        value: llama-3.1-8b-instant
      - key: TOP_K_RESULTS
        value: "20"
      - key: LLM_MAX_TOKENS
        value: "2048"
      - key: PYTHON_VERSION
        value: "3.11"
