services:
  - type: web
    name: lexiquery-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: LLM_MODEL
        value: llama-3.1-8b-instant
      - key: TOP_K_RESULTS
        value: "20"
      - key: LLM_MAX_TOKENS
        value: "2048"
      - key: PYTHON_VERSION
        value: "3.11"
